from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Mapping

from tims_frontier.construction.builders import TrialBuildSpec


RESULT_SCHEMA_VERSION = "1.0"
TRIAL_RESULTS_FIELDNAMES = [
    "result_schema_version",
    "study_id",
    "run_id",
    "trial_id",
    "family",
    "family_role",
    "family_trial_index",
    "optuna_study_name",
    "optuna_trial_number",
    "status",
    "failure_code",
    "failure_message",
    "global_seed",
    "trial_seed",
    "input_signal_seed",
    "mask_seed",
    "morphology_seed",
    "beta_prime",
    "theta",
    "gamma",
    "m0",
    "Nvirt",
    "geometry_mode",
    "morphology_scheme",
    "morphology_n_instances",
    "morphology_beta_spread",
    "morphology_weights_mode",
    "MC",
    "KR",
    "GR",
    "CQ",
    "CQ_formula",
    "runtime_seconds",
    "started_at_utc",
    "finished_at_utc",
    "resolved_config_path",
    "trial_log_path",
]
FRONTIER_POINTS_FIELDNAMES = [
    "result_schema_version",
    "study_id",
    "run_id",
    "frontier_point_id",
    "frontier_scope",
    "endpoint_ref",
    "family",
    "family_role",
    "source_trial_id",
    "source_optuna_trial_number",
    "MC",
    "CQ",
    "KR",
    "GR",
    "beta_prime",
    "theta",
    "gamma",
    "m0",
    "Nvirt",
    "geometry_mode",
    "morphology_scheme",
    "morphology_n_instances",
    "morphology_beta_spread",
    "morphology_weights_mode",
    "pareto_rank",
    "duplicate_count",
    "frontier_algorithm",
    "dominance_epsilon",
    "generated_at_utc",
]
FAILURE_LOG_FIELDNAMES = [
    "result_schema_version",
    "study_id",
    "run_id",
    "trial_id",
    "family",
    "optuna_trial_number",
    "status",
    "failure_code",
    "exception_type",
    "message",
    "traceback_path",
    "trial_seed",
    "timestamp_utc",
]


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def make_trial_record(
    *,
    resolved_config: Mapping[str, Any],
    build_spec: TrialBuildSpec,
    trial_id: str,
    family_trial_index: int,
    optuna_study_name: str,
    optuna_trial_number: int | None,
    status: str,
    seed_bundle: Mapping[str, int],
    sampled_params: Mapping[str, float],
    metrics: Mapping[str, Any] | None = None,
    failure_code: str | None = None,
    failure_message: str | None = None,
    runtime_seconds: float | None = None,
    started_at_utc: str | None = None,
    finished_at_utc: str | None = None,
    trial_log_path: str | None = None,
) -> dict[str, Any]:
    """Build a trial-results row that matches the result schema."""

    metrics = dict(metrics or {})
    paths = resolved_config["storage"]["paths"]
    morphology = build_spec.morphology
    return {
        "result_schema_version": RESULT_SCHEMA_VERSION,
        "study_id": resolved_config["study"]["study_id"],
        "run_id": resolved_config["run"]["run_id"],
        "trial_id": trial_id,
        "family": build_spec.family,
        "family_role": build_spec.family_role,
        "family_trial_index": family_trial_index,
        "optuna_study_name": optuna_study_name,
        "optuna_trial_number": optuna_trial_number,
        "status": status,
        "failure_code": failure_code,
        "failure_message": failure_message,
        "global_seed": resolved_config["execution"]["seed_policy"]["global_seed"],
        "trial_seed": seed_bundle["trial_seed"],
        "input_signal_seed": seed_bundle["input_signal_seed"],
        "mask_seed": seed_bundle["mask_seed"],
        "morphology_seed": seed_bundle.get("morphology_seed") if build_spec.family == "heterogeneous" else None,
        "beta_prime": sampled_params["beta_prime"],
        "theta": sampled_params["theta"],
        "gamma": sampled_params["gamma"],
        "m0": sampled_params["m0"],
        "Nvirt": build_spec.reservoir_params.Nvirt,
        "geometry_mode": build_spec.geometry_mode,
        "morphology_scheme": morphology.scheme,
        "morphology_n_instances": morphology.n_instances,
        "morphology_beta_spread": morphology.beta_spread,
        "morphology_weights_mode": morphology.weights_mode,
        "MC": metrics.get("MC"),
        "KR": metrics.get("KR"),
        "GR": metrics.get("GR"),
        "CQ": metrics.get("CQ"),
        "CQ_formula": metrics.get("CQ_formula", "KR_minus_GR"),
        "runtime_seconds": runtime_seconds,
        "started_at_utc": started_at_utc or _utc_now_iso(),
        "finished_at_utc": finished_at_utc,
        "resolved_config_path": paths["resolved_config_path"],
        "trial_log_path": trial_log_path,
    }


def make_frontier_record(
    *,
    resolved_config: Mapping[str, Any],
    source_trial: Mapping[str, Any],
    frontier_point_id: str,
    duplicate_count: int,
    generated_at_utc: str | None = None,
) -> dict[str, Any]:
    """Build a frontier-points row from a source trial record."""

    return {
        "result_schema_version": RESULT_SCHEMA_VERSION,
        "study_id": source_trial["study_id"],
        "run_id": source_trial["run_id"],
        "frontier_point_id": frontier_point_id,
        "frontier_scope": "family_primary_endpoint",
        "endpoint_ref": "comparison.primary_endpoint",
        "family": source_trial["family"],
        "family_role": source_trial["family_role"],
        "source_trial_id": source_trial["trial_id"],
        "source_optuna_trial_number": source_trial["optuna_trial_number"],
        "MC": source_trial["MC"],
        "CQ": source_trial["CQ"],
        "KR": source_trial["KR"],
        "GR": source_trial["GR"],
        "beta_prime": source_trial["beta_prime"],
        "theta": source_trial["theta"],
        "gamma": source_trial["gamma"],
        "m0": source_trial["m0"],
        "Nvirt": source_trial["Nvirt"],
        "geometry_mode": source_trial["geometry_mode"],
        "morphology_scheme": source_trial["morphology_scheme"],
        "morphology_n_instances": source_trial["morphology_n_instances"],
        "morphology_beta_spread": source_trial["morphology_beta_spread"],
        "morphology_weights_mode": source_trial["morphology_weights_mode"],
        "pareto_rank": 0,
        "duplicate_count": duplicate_count,
        "frontier_algorithm": resolved_config["analysis"]["frontier"]["algorithm"],
        "dominance_epsilon": resolved_config["analysis"]["frontier"]["dominance_epsilon"],
        "generated_at_utc": generated_at_utc or _utc_now_iso(),
    }


def make_failure_record(
    *,
    resolved_config: Mapping[str, Any],
    trial_id: str,
    family: str,
    optuna_trial_number: int | None,
    failure_code: str | None,
    exception_type: str | None,
    message: str | None,
    traceback_path: str | None,
    trial_seed: int,
    status: str = "failed",
    timestamp_utc: str | None = None,
) -> dict[str, Any]:
    """Build a failure-log record that matches the result schema."""

    return {
        "result_schema_version": RESULT_SCHEMA_VERSION,
        "study_id": resolved_config["study"]["study_id"],
        "run_id": resolved_config["run"]["run_id"],
        "trial_id": trial_id,
        "family": family,
        "optuna_trial_number": optuna_trial_number,
        "status": status,
        "failure_code": failure_code,
        "exception_type": exception_type,
        "message": message,
        "traceback_path": traceback_path,
        "trial_seed": trial_seed,
        "timestamp_utc": timestamp_utc or _utc_now_iso(),
    }
